### ISSUE TITLE
addTestDevice support

### ISSUE THREAD

**Issue by ZenoKugy** [appfeel/admob-google-cordova#12]
When testing apps with admob, Google requires users to use 
AdRequest.Builder.addTestDevice("deviceIDhere")
This request appears also in the LogCat output.

It is simple to achieve this while programming an app using Java, but what when using cordova + appfeel.

Is it possible? Would it be possible to add a feature to achieve this?

**Comment by appfeel** [comment]
Hi @ZenoKugy, this feature is already available ([see setOptions documentation here](https://github.com/appfeel/admob-google-cordova/wiki/setOptions)):

    admob.setOptions({
      publisherId:          "ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB",  // Required,
      // ... Other optional options
      isTesting:            true
    });
