### ISSUE TITLE
iOS Interstitial ad closed returns adType banner

### ISSUE THREAD

**Issue by hannad93** [appfeel/admob-google-cordova#14]
Hello

I have a Sencha Touch/Cordova project and I'm using this plugin. It works great on android, but there seems to be a problem with iOS interstitial ads.

I call the `admob.requestInterstitialAd` providing it with the publisherId being the interstitial ad unit id, and the isTesting flag set to true.

When the `admob.events.onAdLoaded` event is fired, I checked the type of the ad in case of interstitial, and it was <b>interstitial</b>, however when the `admob.events.onAdClosed` event is fired, the ad type in the parameters is <b>banner</b>.

Any help with this?

Thank you :)

**Comment by appfeel** [comment]
Hi @hannad93, thanks for the issue.
Solved in https://github.com/appfeel/admob-google-cordova/commit/8e35414c98411ff0031a3792254a3e90a85b4c2f

**Comment by hannad93** [comment]
Thank you!
