### ISSUE TITLE
Adds not showing on Android

### ISSUE THREAD

**Issue by garfield185** [appfeel/admob-google-cordova#15]
Hi, this is not working on android. 
I took the test project and remove all the functionalities in order to create a blank and basic app with adds, it works in iOS (emulator and real device), but not in android.

**Comment by seanwilson** [comment]
Hi, did you get this working on Android?

We’ve got it set up and working perfectly on iOS using the sample code from the Readme page.

However, we are having problems loading and displaying ads on Android. 

The errors we are getting, in both a debug APK and a release APK are:

<strong>CsiReporterFactory: CSI is not enabled. No CSI reporter created.</strong>

and

<strong>Use AdRequest.Builder.addTestDevice("C0XXX7F7B90EEC5CCDB7EAB682EXXXXX”) to get test ads on this device.</strong>

Everything is set up correctly, using a different admob pubid for Android. 

We’ve spent a lot of time Googling the error messages and it seems quite a few people are having similar issues.

Any help much appreciated!

Many thanks,

Sean

PS Our test device is a Samsung Galaxy Tab 2 running Android 4.0.3 with Google Play services version 7.3.29. Cordova version is 3.6.3

We have a second device, the same as above but running Android 4.2.2

**Comment by garfield185** [comment]
Hi, I wish I could help... 

I created a blank project to get the ads working. It works on iOS but not on Android. 

Then I add my application, and it started working on Android as well.  I can't say why though...

**Comment by seanwilson** [comment]
Haha, thanks - glad you got it working!

Hopefully somebody here can enlighten us :)

**Comment by garfield185** [comment]
I am working in a new project as well.

I will check what happens with this one as soon as I start adding the code.
Maybe it helps.

**Comment by seanwilson** [comment]
OK, I got it working! 

I was using an older version of the Android SDK which didn’t support Google Play Services.

Upgrading to a newer SDK for me was a major nightmare though, due to a well-known packaging problem, but I finally got it updated thanks to this post: https://code.google.com/p/android/issues/detail?id=72912#c18

Happy days :)

**Comment by appfeel** [comment]
I've made some changes affecting cordova for android@4.0.0 (it wasn't supported until com.admob.google@4.0.1: https://github.com/appfeel/admob-google-cordova/commit/49ad957327e5317cc6d72c2aa4cae8640508dfaa)
@garfield185 could you tell if it's working on the new project? I would close this issue.
