### ISSUE TITLE
Can't change the size of the ad while testing

### ISSUE THREAD

**Issue by KhaledElAnsari** [appfeel/admob-google-cordova#16]
Hello..

I tried to change the size of the ad but it didn't work

I wrote this ( adSize: admob.AD_SIZE.IAB_MRECT ) also I tried to put it between double quotation like this ( adSize: 'admob.AD_SIZE.IAB_MRECT' ) but it also didn't work, any idea why?

I also tried to replace the method IAB_MRECT with MEDIUM_RECTANGLE from google (can be found here : https://developers.google.com/mobile-ads-sdk/docs/admob/android/banner#size)

P.S.: I'm using phonegap build with version 3.3.0 of phonegap, and I'm testing on Sony Xperia z2

**Comment by appfeel** [comment]
Hi @KhaledElAnsari,
Please, could you paste your javascript code?

**Comment by KhaledElAnsari** [comment]
nothing fancy 

```javascript
var options = {
		publisherId: "NONE",
		interstitialAdId: "NONE",
		bannerAtTop: false,
		autoShowBanner: true,
		autoShowInterstitial: true,
		isTesting: true,
		adSize: 'admob.AD_SIZE.IAB_MRECT'
	};
document.addEventListener("deviceready", onDeviceReady, true);
function onDeviceReady() {
	document.addEventListener("backbutton", onBackKeyDown, false);

	var pushNotification = window.plugins.pushNotification;
	if (device.platform == 'android' || device.platform == 'Android') {
		pushNotification.register(successHandler, errorHandler,{"senderID":"610878617425","ecb":"onNotificationGCM"});
	}
	else {
		pushNotification.register(this.tokenHandler,this.errorHandler,   {"badge":"true","sound":"true","alert":"true","ecb":"onNotificationAPN"});
	}
	admob.createBannerView(options, adsuccess, adfail);
}
```

**Comment by appfeel** [comment]
The code you pasted won't work and will fall back to smart_banner, as you are using quotes in adSize (I've seen in the original question you said you tried without quotes, which is the correct way).

You should either use  `adSize: admob.AD_SIZE.IAB_MRECT` (without quotes) or `admob: "IAB_MRECT"`. Could you try the last option, to discard possibilities?

I've been doing some testing in android/ios with different options and it's rendering 300x250 right well:

![admob-cordova-plugin-test-android](https://cloud.githubusercontent.com/assets/8643279/7898844/9b52e540-070d-11e5-8d4e-e6f90ec919f4.png)

And for iOS too:

![admob-cordova-plugin-test-ios](https://cloud.githubusercontent.com/assets/8643279/7898910/5ec880a6-070f-11e5-9c51-2ea96849efcf.png)

**Comment by KhaledElAnsari** [comment]
it worked! thanks man. oh btw (just to make sure) there's no chance to put the ad inside of a div of mine or at the side of the screen instead of top/bottom of the screen, right?

**Comment by appfeel** [comment]
@KhaledElAnsari :) 
Not possible with this plugin (as it shows native ads). The only chance would be to use web ads (adsense). This is against Google Policy and your Android app could be rejected. In iOS I'm almost sure that your app would be rejected.

I'm considering to implement free positioning of the ad on the screen, but no plans yet on when it would be implemented, I will let you know.
