### ISSUE TITLE
Phonegap build doesn't support the plugin!

### ISSUE THREAD

**Issue by KhaledElAnsari** [appfeel/admob-google-cordova#17]
Hello

Yesterday the phonegap build stopped working, i notified them and tried everything i can do but nothing helped. today i removed this plugin from my config.xml file and the build worked!

Just wanted to tell you about this problem, hope you fix it 'cause this plugin is good enough for me.

P.S. : the problem was with building the apk, the windows phone version was built just fine

**Comment by appfeel** [comment]
Could you paste the log error from Phonegap please?

**Comment by KhaledElAnsari** [comment]
BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

**Comment by jpmp2139** [comment]
```
-pre-compile:

-compile:
    [javac] Compiling 9 source files to /project/bin/classes
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:422: error: cannot find symbol
    [javac]                 ((ViewGroup) webView.getView().getParent()).addView(adViewLayout, params);
    [javac]                                     ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:432: error: cannot find symbol
    [javac]               ViewGroup wvParentView = (ViewGroup) webView.getView().getParent();
    [javac]                                                           ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:439: error: cannot find symbol
    [javac]                 wvParentView.removeView(webView.getView());
    [javac]                                                ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:442: error: cannot find symbol
    [javac]                 webView.getView().setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, 1.0F));
    [javac]                        ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:443: error: cannot find symbol
    [javac]                 parentView.addView(webView.getView());
    [javac]                                           ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] 5 errors

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 8 seconds

```

**Comment by appfeel** [comment]
Thanks @jpmp2139, I see, this is a problem with phonegap cordova version. I will try to fix, but meanwhile you can use previous plugin version: 

```xml
<gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"/>
```

For the moment there are no big issues solved in next versions. I'll keep you informed when available.

**Comment by jpmp2139** [comment]
Thanks

**Comment by KhaledElAnsari** [comment]
thanks @appfeel and btw the plugin adds a lot to the size of the apk can you do something about it?

**Comment by appfeel** [comment]
:)

@KhaledElAnsari not really, this is because of google play services lib, which is 14.4MB for iOS and 7.5MB for android...
You are talking about those sizes right? If it's more than this, then it's not due to this plugin.

**Comment by KhaledElAnsari** [comment]
@appfeel no i've never reach that size, after adding the plugin my app become about 2mb bigger! I tried other plugins and they add only 1mb! that's why I'm asking

**Comment by moeenuddin** [comment]
@appfeel  I am building it with ionic. I have not been successful yet. I am getting the similar issue and unable to build project. @KhaledElAnsari  How can i go to previous workable plugin for ionic or cordova? Advise please.

**Comment by KhaledElAnsari** [comment]
@moeenuddin  I believe this will help you man

http://cordova.apache.org/news/2013/10/21/cordova-registry.html

**Comment by sggray** [comment]
I had the same issue at @KhaledElAnsari, switching to the old version allowed me to build again. Thanks for the help!

**Comment by sggray** [comment]
I had the same issue as @KhaledElAnsari, switching to the old version allowed me to build again. Thanks for the help!

**Comment by cBevilaqua** [comment]
Im using Ionic and the solution presented by @moeenuddin worked to me. Thanks!

**Comment by appfeel** [comment]
For ionic platform you should update your android platform:

```
ionic platform update android@4.0.0
```

**Comment by appfeel** [comment]
@KhaledElAnsari please see https://github.com/appfeel/admob-google-cordova/issues/18 regarding to plugin size

**Comment by Sean04** [comment]
Within the last month, it seems this plugin broke. I'm using what you had recommended above:

`<gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"/>`

Errors from the log:

`BUILD FAILED`
`/home/ec2-user/android-sdk/tools/ant/build.xml:888: The following error occurred while executing this line:`
`/home/ec2-user/android-sdk/tools/ant/build.xml:890: The following error occurred while executing this line:`
`/home/ec2-user/android-sdk/tools/ant/build.xml:902: The following error occurred while executing this line:`
`/home/ec2-user/android-sdk/tools/ant/build.xml:283: null returned: 2`

Any ideas?

**Comment by bheijns** [comment]
We are facing the same issue for over some time now.. Our update release is scheduled for the upcoming week. Is there any estimation on a fix or proper workaround (mentioned one does not work)?

**Comment by SeanFromIT** [comment]
I am receiving same error as Sean04, trying to use the recommended older version in PhoneGap.

**Comment by KhaledElAnsari** [comment]
@appfeel please fix it as soon as possible

**Comment by scottopolis** [comment]
Hi, thanks for your plugin!  I am using Phonegap Build version 3.6.3 (also tried 3.7.0) with your plugin, with this setting:

    <gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"/>

The Android app will not build, it just says "Oh geez. Your build failed. Sorry, but a problem occurred on the build server."  If I remove the plugin, it works fine.

Is there anything I can do?

**Comment by miqmago** [comment]
We have recently deployed a version in phonegap build plugin repository. Please, could you try with the following config?

```xml
<gap:plugin name="com.admob.google" version="2.0.14"/>
```

**Comment by appfeel** [comment]
We have moved to nom registry, please use this plugin like this in phoengap:

```
<gap:plugin name="cordova-admob" source="npm"/>
```

**Comment by sggray** [comment]
Not sure why this got closed. I just tried to build again using "<gap:plugin name="cordova-admob" source="npm"/>" and the android build still fails. 

@appfeel any ideas? Thanks

**Comment by appfeel** [comment]
@sggray which version of phonegap are you using? Could you paste the log?

**Comment by gonzamateos** [comment]
I'm using Phonegap 3.7, trying with name="cordova-admob" source="npm" I get this error:
"Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: AdMobAds.java"

I also tried with these two, but does not work:
gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"
gap:plugin name="com.admob.google" version="4.0.8"

Please I need help, I'm in a hurry

**Comment by gonzamateos** [comment]
With 
gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"

I get:
Error - Plugin error (you probably need to remove plugin files from your app): npm http GET http://registry.cordova.io/com.admob.google/2.0.14 npm http 200 http://registry.cordova.io/com.admob.google/2.0.14 npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.admob.google/-/com.admob.google-2.0.14.tgz npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/com.admob.google/-/com.admob.google-2.0.14.tgz Failed to install 'com.admob.google':Error: Expected plugin to have ID "android.support.v4" but got "cordova-android-support-v4". at checkID (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/fetch.js:164:15) at /home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/cordova-lib/src/plugman/fetch.js:148:9 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:749:13) at /home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:557:44 at flush (/home/ec2-user/.npm/lib/node_modules/plugman-npm/node_modules/q/q.js:108:17) at process._tickCallback (node.js:442:13) Expected plugin to have ID "android.support.v4" but got "cordova-android-support-v4".

**Comment by gonzamateos** [comment]
@appfeel does it gives you any ideas?

**Comment by gonzamateos** [comment]
@appfeel, could you please rollback or make it works on Phonegap Build. It was working perfect a few days ago with `<gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"/>`

**Comment by cassioscofield** [comment]
+1

**Comment by Protonentomate** [comment]
Any updates?

**Comment by sdhvlz** [comment]
Same here. Any ideas?

**Comment by gonzamateos** [comment]
I have a gun in my head. I can't configure adMob with any plugin, at the moment no one is working for me and I have to finish a project. Is there any idea for this or another plugin to do the same? just adMob banners in the bottom of the screen. I'm using build.phonegap.

**Comment by bheijns** [comment]
You may use this plugin:
<gap:plugin name="com.ads.tappx" source="plugins.cordova.io" version="1.0.2"/>

Put the settings to 100% Google Admob ads.
This works for me.

**Comment by Protonentomate** [comment]
Phonegap Build is working for me when i use the npm Source
```
<gap:plugin name="cordova-admob" source="npm"/>
```

**Comment by gonzamateos** [comment]
Wich version of phonegap are you using? I get:
`Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: AdMobAds.java - You can fix this here`

I attached my config.xml

Thanks

![config xml](https://cloud.githubusercontent.com/assets/7100505/10455765/a275c982-7193-11e5-96e3-70ab8c353398.jpg)

**Comment by gonzamateos** [comment]
btw... it works on iOS, the problem is with Android

**Comment by ingalb** [comment]
Hello, 
Remove you phonegap version (Line 11)  and it should function correctly.

**Comment by gonzamateos** [comment]
on this way, I have problems with the file-transfer plugin
`Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: FileTransfer.java - You can fix this here`

Don't you know which version should I use for the admob plugin? so I can try to make both plugins work together.

**Comment by bheijns** [comment]
You need to upgrade to the new npm plugins.

**Comment by gonzamateos** [comment]
Ok, thanks... I so will upgrade all the other plugins. Thanks again

**Comment by bheijns** [comment]
No worries! You're welcome.

In near future I will launch my new phonegap.info website. I think many people are in the need of proper documentation and help in case of any issues related to phonegap.

**Comment by gonzamateos** [comment]
It will be awsome! thanks for doing that too.

**Comment by bampakoa** [comment]
Hi,

What if someone does not want to upgrade to the new npm plugins? Is it mandatory to do so for the plugin version 2.0.14 to work?

Thanks

**Comment by kaarele** [comment]
I'm one of those who would prefer not upgrading to the npm plugins. Are there any ways to just get it back working again?

**Comment by appfeel** [comment]
@kaarele then you need to use specific version:

```xml
<gap:plugin name="cordova-admob" source="plugins.cordova.io" version="2.0.14"/>
```

```
cordova plugin add cordova-admob@2.0.14
```

I don't recommend this anyway, as cordova is now 5.x android and 4.x iOS, and lots of features may have been fixed/changed.

**Comment by appfeel** [comment]
Also created a fork for phonegap build. You can use the last version with 

```xml
<gap:plugin name="phonegap-admob" source="npm"/>
```

I will keep both updated 😄
