### ISSUE TITLE
Remove demo files from the built apk file

### ISSUE THREAD

**Issue by astroanu** [appfeel/admob-google-cordova#18]
each time the apk is buit the demo files also gets included adding extra 3mb to the apk file. is there a way to skip the png files ? or maybe i think they should not be there in the first place.

**Comment by appfeel** [comment]
Thanks @astroanu I will remove then
this answers the question from @KhaledElAnsari

Will be implemented next days

**Comment by astroanu** [comment]
thank you .

**Comment by appfeel** [comment]
https://github.com/appfeel/admob-google-cordova/commit/faa5c7945c0aa39c58fddbeba56761b75d2fd65a
