### ISSUE TITLE
Error Building with Telerik AppBuilder for iOS

### ISSUE THREAD

**Issue by est1974** [appfeel/admob-google-cordova#19]
Hi there!

A couple weeks back this worked great, but now when I build, I am getting the following errors:

```
	Error: [xcode-build] Compile /tmp/builds/eEVkkQzlBDFmHqJIIW/app/Cordova350/Plugins/tappx-phonegap/CDVAdMobAds.m: In file included from /tmp/builds/eEVkkQzlBDFmHqJIIW/app/Cordova350/Plugins/tappx-phonegap/CDVAdMobAds.m:29:
In file included from /tmp/builds/eEVkkQzlBDFmHqJIIW/app/Cordova350/Plugins/tappx-phonegap/CDVAdMobAds.h:33:
Cordova350/Plugins/com.ios.libgoogleadmobads/GoogleMobileAds.framework/Headers/GADInterstitial.h:24:80: error: expected ':'

	Error: [xcode-build] Compile /tmp/builds/eEVkkQzlBDFmHqJIIW/app/Cordova350/Plugins/tappx-phonegap/CDVAdMobAdsAdListener.m: In file included from /tmp/builds/eEVkkQzlBDFmHqJIIW/app/Cordova350/Plugins/tappx-phonegap/CDVAdMobAdsAdListener.m:28:
In file included from /tmp/builds/eEVkkQzlBDFmHqJIIW/app/Cordova350/Plugins/tappx-phonegap/CDVAdMobAds.h:33:
Cordova350/Plugins/com.ios.libgoogleadmobads/GoogleMobileAds.framework/Headers/GADInterstitial.h:24:80: error: expected ':'
	Error: 'Build failed with error code 2'
```
Just wanted to bring it to your attention.

**Comment by appfeel** [comment]
Hi @est1974, it seems a problem with the google framework itself, not with the plugin. I've been also reviewing it but cannot find what Telerik is complaining about: https://github.com/appfeel/google-iosadmobads/blob/master/src/ios/GoogleMobileAds.framework/Versions/A/Headers/GADInterstitial.h#L24

This is a google framework header which is working in Xcode without giving any problem. I'm not really used to Telerik AppBuilder, could you ask them a better explanation of the issue so I could give you better support?

Meanwhile you could use the version 2.0.14 of the plugin (which integrates Google SDK v7.0), but in my opinion is let's also ask to Telerik what is going on.

**Comment by appfeel** [comment]
Right now this issue should be resolved with npm version, could you please check it?

```
cordova plugin add cordova-admob
```
