### ISSUE TITLE
When running in the iOS simulator, real adverts are displayed even when isTesting = true.

### ISSUE THREAD

**Issue by MikeDocker** [appfeel/admob-google-cordova#24]
Hi

Great plug-in. Finding it really useful.

One thing I have noticed is that when isTesting = true, I still see real adverts when running in the iOS simulator.

I have done some research and have the following suggestion to contribute.

The release notes for "SDK for AdX Users on iOS" (see https://developers.google.com/mobile-ads-sdk/docs/adx/ios/rel-notes) say

7.2.1	2015‑04‑30

"Simulators once again load live ads by default. Add kGADSimulatorID to the testDevices property on GADRequest to get test ads on simulators."

I modified __buildAdRequest in CDVAdMobAds.m near line 704 so it looks like

request.testDevices =
[NSArray arrayWithObjects:
admobDeviceId, kGADSimulatorID, @"dabe...snip...2b3e",
nil];

Now when isTesting = true, I see test adverts when using the iOS simulator as well as when running on my iPad (UUID beginning dabe etc).

This is not my area of expertise, but I wonder if a change along the lines of what I have suggested might be worth considering.

Best wishes

Mike

**Comment by ilovett** [comment]
I'm getting this as well.  From my console:

```
<Google> To get test ads on this device, call: request.testDevices = @[ kGADSimulatorID ];
```

It would be great if that chunk of figured out it's own device id (whether its simulator or not) and passed the required information.

**Comment by appfeel** [comment]
Once uppon a time it was there, then I removed, don't ask me why. Now it's there again. Will see if any issues make me remember why I removed 😄 Thanks anyway!
