### ISSUE TITLE
After click Admob and turn back: "App has stopped"

### ISSUE THREAD

**Issue by calebeaires** [appfeel/admob-google-cordova#29]
When user click on Admob, goes to "Chrome" and after this user turn back, the app crash and show this: "App has stopped".

**Comment by appfeel** [comment]
Please, could you provide logcat?
I can't reproduce the crash: I've opened test app, loaded banner ads (test), click on an ad, went to chrome, went back / closed chrome (tried both situations), then the app appeared normally from background.

I'm almost sure you're testing this in a tablet. Did you test it with real ads or test ads?
Also I would appreciate the android version you're using to test it.

**Comment by calebeaires** [comment]
I will close this. This problem has an webview related issue on Android 5.1. I havent get this problem again after webview update.
