### ISSUE TITLE
I have error when build ipa for ios

### ISSUE THREAD

**Issue by nichekeys** [appfeel/admob-google-cordova#30]
Build with Intel XDK R2611
cordova-admob/CDVAdMobAds.h:31:9: fatal error: 'GoogleMobileAds/GADAdSize.h' file not found

**Comment by pouriaMaleki** [comment]
+1

**Comment by colonna-mike** [comment]
+1 any idea why?

**Comment by miqmago** [comment]
See https://github.com/appfeel/admob-google-cordova/issues/6#issuecomment-81850649

and https://github.com/appfeel/admob-google-cordova/issues/39#issuecomment-257080831

Please reopen if didn't help
