### ISSUE TITLE
don't work with com.adobe.plugins.gaplugin

### ISSUE THREAD

**Issue by draig** [appfeel/admob-google-cordova#33]
I use phonegap builder and when i include 
`<gap:plugin name="cordova-admob" source="npm" version="4.1.6" />`
`<gap:plugin name="com.adobe.plugins.gaplugin" version="2.4.0" />`
into config.xml build failed.
     [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/analytics/internal/Command$1;
       [dx] 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:277)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:245)
       [dx] 	at com.android.dx.command.Main.main(Main.java:106)
       [dx] 

BUILD FAILED
/android-sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/android-sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/android-sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/android-sdk/tools/ant/build.xml:283: null returned: 2

Total time: 42 seconds

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: ant with args: debug,-f,/project/build.xml

**Comment by aphil** [comment]
I have the same error, did you find any workaround?

**Comment by draig** [comment]
I just remove gaplugin

**Comment by draig** [comment]
but how I understand that pr can fix this bug
https://github.com/appfeel/admob-google-cordova/pull/32
but it didn't approve

**Comment by appfeel** [comment]
@draig sorry for the delay, already merged but this is still not working for me (in local cordova with GAPlugin)

**Comment by appfeel** [comment]
Sorry for the delay, already approved the pr, now should be fixed

**Comment by appfeel** [comment]
For phonegap build use this plugin, it's a fork and will keep both updated:

```xml
<gap:plugin name="phonegap-admob" source="npm"/>
```
