### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by MorpheusZero** [appfeel/admob-google-cordova#34]
I've been working on this for about 3 hours now and I've given up. I've used AdMob on Android Studio, Xamarin Studio, and Unity before with different plugins--no issues. I've been following tutorial after tutorial and trying everything I can in the documentation and I can't figure out what I'm doing wrong. I have the code below, and when the app loads on my phone--Samsung Galaxy Note 3--nothing happens. No banner is loaded. I'm not saying this doesn't work, I'm just saying I don't think it's as easy as presented with added a few lines of code because I can't get it to work for myself.

        function onDeviceReady() {
            document.removeEventListener('deviceready', onDeviceReady, false);

        document.addEventListener('pause', onPause.bind(this), false);
        document.addEventListener('resume', onResume.bind(this), false);

        admob.setOptions({
            publisherId: "ca-app-pub-XX",
            bannerAtTop: true, // set to true, to put banner at top
            overlap: true, // set to true, to allow banner overlap webview
            offsetStatusBar: true, // set to true to avoid ios7 status bar overlap
            isTesting: true, // receiving test ads (do not test with real ads as your account will be banned)
            autoShowBanner: true // auto show banners ad when loaded
        });

        admob.createBannerView();
    };

**Comment by arjankuijpers** [comment]
is the admob object undefined or null ?

**Comment by coolnd3adly** [comment]
mine says undefined

**Comment by appfeel** [comment]
Sorry for the delay. This may be a problem of testing in browser. In real device / emulator should not happen. Please let me know and reopen if not.
