### ISSUE TITLE
Using timed interstitial in Phonegap app - how to prevent from reloading with page changes?

### ISSUE THREAD

**Issue by jamminjames** [appfeel/admob-google-cordova#37]
I have a Phonegap Build created app that uses jquery.mobile, and am using the timed interstitial ads (function onAdLoaded). The problem is, every time I load a new page, it seems to reset the timer and shows an ad immediately. How can I prevent that, and keep the timer on schedule?

**Comment by jamminjames** [comment]
I think I've got the wrong plugin, I'm using cordova-admob, sorry about that.

**Comment by bryanwokich** [comment]
This is just a JS question. Many (most?) mobile JS apps are written using a single-page app.  There is no refresh. 

Page refreshes will always stop your JS.  

I would look into putting your timer into a WebWorker.

**Comment by miqmago** [comment]
Following @bryanwokich idea, maybe something like https://github.com/wnyc/cordova-plugin-sleeptimer could also help you. This will set-up a native sleeper but you'll need to be carefull not to leave timer activated when user leaves the app, as it may cause crashes.

Personally I think that html5 WebWorker is a better solution, but never tried before. You can take a look at http://www.html5rocks.com/en/tutorials/workers/basics/
