### ISSUE TITLE
Cordova admob use 

### ISSUE THREAD

**Issue by Resham143** [appfeel/admob-google-cordova#38]
every time i m trying to use admob i get 
![fafdaf](https://cloud.githubusercontent.com/assets/13194618/12879955/af311292-ce60-11e5-880f-63e783091bf1.PNG)
work to work on that 
and my code is angular.module('app', ['onsen', 'ui.bootstrap', 'ng-autocomplete','admobModule'])
.config(['admobSvcProvider', function (admobSvcProvider)
{
    admobSvcProvider.setOptions
        ({
            publisherId: 'ca-app-pub-5529525978454334/3896374806',
            tappxIdAndroid: '/120940746/Pub-8303-Android-5260',
            interstitialAdId: 'ca-app-pub-3940256099942544/1033173712',
            tappxShare: 0.5,
            bannerAtTop: true,
            

        });
    admobSvcProvider.setPrefix('myTag~');
}])
.run(['admobSvc', function (admobSvc) {
    admobSvc.createBannerView();
    //document.addEventListener("deviceready", onDeviceReady, false);
    //$rootScope.$on(admobSvc.events.onAdOpened, function onAdOpened(evt, e) {
    //    console.log('adOpened: type of ad:' + e.adType);
    //});
}])

**Comment by appfeel** [comment]
This is because you are using browser to debug. It will work in real app. Also I recommend you to use internal server. Note that I'm using `phonegap` instead of `cordova`, maybe it's a problem just of my computer, maybe not...

```
$ phonegap serve
```

Also you may need to add browser platform:

```
$ cordova platform add browser
```
