### ISSUE TITLE
You are currently using version 7.3.1 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.

### ISSUE THREAD

**Issue by appplumbr** [appfeel/admob-google-cordova#39]
when building in Xcode iOS 9.X and in Ionic CLI (iOS 9.X) I get below console errors:

is this ad mob plugin using the latest SDK?

Failed to receive ad with error: Request Error: Invalid ad request parameter(s). Check the Xcode console for details.
2016-02-25 20:37:07.072 [711:92268] <Google:HTML> You are currently using version 7.3.1 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.

-canOpenURL: failed for URL: "kindle://home" - error: "This app is not allowed to query for scheme kindle"

[CDVAdMobAdsAdListener adView:didFailToReceiveAdWithError:]: Failed to receive ad with error: Request Error: Invalid ad request parameter(s). Check the Xcode console for details.

**Comment by appfeel** [comment]
Yeha, thanks. Working on it, not very sure if it's time to update the sdks... Will see, as old ones are working fine, but if some issues are appearing we'll need to cross fingers and update to latest...

**Comment by bflopez** [comment]
This is happening to me as well and preventing any ads from showing up. Is this a race condition?

**Comment by miqmago** [comment]
`cordova-admob~4.1.15` is now updated to Firebase (7.13.1)

To update the plugin you should remove the plugin ad add it again:

```
$ cordova plugin rm cordova-admob
$ npm cache clear
$ cordova plugin add cordova-admob
```

Sometimes removing the plugin causes an error (it's been reported to cordova https://issues.apache.org/jira/browse/CB-12083).

If that happens, remove first `cordova-libgoogleadmobads` manually:


```
$ rm plugins/cordova-libgoogleadmobads/ -rf
$ cordova plugin rm cordova-admob
$ npm cache clear
$ cordova plugin add cordova-admob
```
