### ISSUE TITLE
rejecting error occured

### ISSUE THREAD

**Issue by rico345100** [appfeel/admob-google-cordova#40]
when i use this plugin, it saids:

03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.672: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.682: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.692: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.692: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.692: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.692: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.692: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAppPurchaseListener>
03-13 00:44:11.692: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.692: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.702: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.712: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.712: W/System.err(26170): java.lang.NoClassDefFoundError: com.appfeel.cordova.admob.AdMobAdsAdListener
03-13 00:44:11.712: W/System.err(26170): 	at com.appfeel.cordova.admob.AdMobAds.<init>(AdMobAds.java:101)
03-13 00:44:11.712: W/System.err(26170): 	at java.lang.reflect.Constructor.newInstance(Native Method)
03-13 00:44:11.712: W/System.err(26170): 	at java.lang.Class.newInstance(Class.java:1606)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:493)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:170)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:123)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-13 00:44:11.712: W/System.err(26170): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-13 00:44:11.712: W/System.err(26170): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
03-13 00:44:11.712: W/System.err(26170): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-13 00:44:11.712: W/System.err(26170): 	at android.os.Looper.loop(Looper.java:135)
03-13 00:44:11.712: W/System.err(26170): 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-13 00:44:11.712: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.712: W/System.err(26170): java.lang.NoClassDefFoundError: com.appfeel.cordova.admob.AdMobAdsAdListener
03-13 00:44:11.712: W/System.err(26170): 	at com.appfeel.cordova.admob.AdMobAds.<init>(AdMobAds.java:101)
03-13 00:44:11.712: W/System.err(26170): 	at java.lang.reflect.Constructor.newInstance(Native Method)
03-13 00:44:11.712: W/System.err(26170): 	at java.lang.Class.newInstance(Class.java:1606)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:493)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:170)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:123)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
03-13 00:44:11.712: W/System.err(26170): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-13 00:44:11.712: W/System.err(26170): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-13 00:44:11.712: W/System.err(26170): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
03-13 00:44:11.712: W/System.err(26170): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-13 00:44:11.712: W/System.err(26170): 	at android.os.Looper.loop(Looper.java:135)
03-13 00:44:11.712: W/System.err(26170): 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-13 00:44:11.722: I/art(26170): Rejecting re-init on previously-failed class java.lang.Class<com.appfeel.cordova.admob.AdMobAdsAdListener>
03-13 00:44:11.722: W/System.err(26170): java.lang.NoClassDefFoundError: com.appfeel.cordova.admob.AdMobAdsAdListener
03-13 00:44:11.722: W/System.err(26170): 	at com.appfeel.cordova.admob.AdMobAds.<init>(AdMobAds.java:101)
03-13 00:44:11.722: W/System.err(26170): 	at java.lang.reflect.Constructor.newInstance(Native Method)
03-13 00:44:11.722: W/System.err(26170): 	at java.lang.Class.newInstance(Class.java:1606)
03-13 00:44:11.722: W/System.err(26170): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:493)
03-13 00:44:11.722: W/System.err(26170): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:170)
03-13 00:44:11.722: W/System.err(26170): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:123)
03-13 00:44:11.722: W/System.err(26170): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
03-13 00:44:11.722: W/System.err(26170): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
03-13 00:44:11.722: W/System.err(26170): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-13 00:44:11.722: W/System.err(26170): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
03-13 00:44:11.722: W/System.err(26170): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-13 00:44:11.722: W/System.err(26170): 	at android.os.Looper.loop(Looper.java:135)
03-13 00:44:11.722: W/System.err(26170): 	at android.os.HandlerThread.run(HandlerThread.java:61)

admob object is exists but not working i think. this is the js code:

	document.addEventListener('deviceready', function() {
		console.log('device ready');
		console.log(admob);
		// Set AdMobAds options: 
		admob.setOptions({
			publisherId:          "myid",  // Required 
			//interstitialAdId:     "ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII",  // Optional 
			//tappxIdiOs:           "/XXXXXXXXX/Pub-XXXX-iOS-IIII",            // Optional 
			//tappxIdAndroid:       "/XXXXXXXXX/Pub-XXXX-Android-AAAA",        // Optional 
			//tappxShare:           0.5                                        // Optional 
		});
		
		// Start showing banners (atomatic when autoShowBanner is set to true) 
		admob.createBannerView();
		
		// Request interstitial (will present automatically when autoShowInterstitial is set to true) 
		admob.requestInterstitialAd();
	});

used latest cordova. no related issues found. what should i do?

**Comment by appfeel** [comment]
I've updated the plugin to support gradle, please, could you check if it works? Reopen the issue in case it's another problem.
