### ISSUE TITLE
Error - One of your plugins required the gradle android build tool to build

### ISSUE THREAD

**Issue by html5andblog** [appfeel/admob-google-cordova#41]
Recently all my apps have been getting the same message when I try and compile them using PhoneGap Build:

Error - One of your plugins required the gradle android build tool to build - You can fix this here

Is there something else that I need to add to the config.xml to fix this issue?

Any advice here would be great.

Thanks,

Simon

**Comment by appfeel** [comment]
Hi Simon,

I've created a fork of the project to support phonegap build:

```xml
<gap:plugin name="phonegap-admob" source="npm"/>
```

I will keep both repos updated. Please let me know if it works 😄

**Comment by html5andblog** [comment]
Thanks, I'll try it on my next App.
