### ISSUE TITLE
Plugin Source unsupported

### ISSUE THREAD

**Issue by barrydoyle18** [appfeel/admob-google-cordova#42]
I'm failing to build my app using `<gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"/>` because I get `plugin source unsupported: com.admob.google from plugins.cordova.io` error.

Why isn't this working??

**Comment by appfeel** [comment]
Please use 

```xml
<gap:plugin name="cordova-admob" source="npm"/>
```

**Comment by appfeel** [comment]
Sorry my mistake, please use 

```xml
<gap:plugin name="phonegap-admob" source="npm"/>
```
