### ISSUE TITLE
adAdClosed event does not fire on ios

### ISSUE THREAD

**Issue by av01d** [appfeel/admob-google-cordova#45]
I am showing an interstitial ad in my Cordova project. This works great, both on Android and iOS.
The 'onAdLoaded' event is called on both platforms when the ad is on screen.
However, when I close the Ad (hit the X-icon) the onAdClosed event is only called on Android, not on iOS.
Same for the 'resume' event: only called on Android, not on iOS.

```javascript
document.addEventListener(admob.events.onAdClosed, function(e) {
   alert('ad closed');
}, false);

document.addEventListener("resume", function() {
   alert('resume');
}, false);
```

Both alerts do appear on Android, none of them appear on iOS.
How can I detect the user closed the interstitial ad on iOS?
(I am using Cordova 6.1.1 and AdMob plugin version 4.2.9)

**Comment by appfeel** [comment]
@av01d I'm sorry for the late response. I've been testing in iOS 9.2 simulator with test and real ads and I can see the alert. That's quite strange as you say that you're receiving it in Android.

Are the other events working? you can try with

```js
document.addEventListener(admob.events.onAdLoaded, function(e) {
   alert('ad loaded');
}, false);
```
