### ISSUE TITLE
im try plugin but not show ads

### ISSUE THREAD

**Issue by jocker25** [appfeel/admob-google-cordova#46]
app demo run testAdMob_main() and 1 alert show "admob plugin not ready". 
please help me. i try on device Sony xperia Z1 and PhoneGap develop,

**Comment by brainyfarm** [comment]
Be sure to only fire on "deviceready" otherwise it would not work.

I had this problem and just fixed it some minutes ago.

**Comment by miqmago** [comment]
Hope @brainyfarm solves the problem, let me know otherwise. I will also update docs to clarify.

**Comment by jocker25** [comment]
yeah, please update docs for android ^_^, if you upload video is cool!

**Comment by brainyfarm** [comment]
I am glad it worked for you.
I struggled with this for days and I think the docs should be updated indeed.
