### ISSUE TITLE
Error when adding plugin and compiling

### ISSUE THREAD

**Issue by agrapps** [appfeel/admob-google-cordova#47]
Hi, i add this plugin, Im using phonegap 6.2.4 and the command "phonegap run android" to test it on my phone, but when i try to run it send me the following error:

> UNEXPECTED TOP-LEVEL EXCEPTION:
> com.android.dex.DexException: Multiple dex files define Landroid/support/annotat
> ion/AnimRes;
>         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
>         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:43
> 9)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
>         at com.android.dx.command.dexer.Main.run(Main.java:230)
>         at com.android.dx.command.dexer.Main.main(Main.java:199)
>         at com.android.dx.command.Main.main(Main.java:103)
> 
>  FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':transformClassesWithDexForDebug'.
> > com.android.build.api.transform.TransformException: com.android.ide.common.pro
> cess.ProcessException: org.gradle.process.internal.ExecException: Process 'comma
> nd 'C:\Program Files\Java\jdk1.8.0_66\bin\java.exe'' finished with non-zero exit
>  value 2
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output.
> 
> 
> BUILD FAILED
> 
> Total time: 3 mins 57.818 secs
> 
> Error: Error code 1 for command: cmd with args: /s,/c,"C:\wamp\www\phonegap_neta
> s\platforms\android\gradlew cdvBuildDebug -b C:\wamp\www\phonegap_netas\platform
> s\android\build.gradle -PcdvBuildArch=arm -Dorg.gradle.daemon=true -Pandroid.use
> DeprecatedNdk=true"

Can somebody tell me whats wrong
Thanks a lot

**Comment by ibrahimAboelsuod** [comment]
I have the same problem

**Comment by laziaf** [comment]
+1

**Comment by miqmago** [comment]
That was probably related to old sdk. Right now it uses gradle and should not happen, please reopen otherwise
