### ISSUE TITLE
Auto show Interstitials

### ISSUE THREAD

**Issue by rigobertomolina** [appfeel/admob-google-cordova#49]
Does this plugin auto show Interstitials? As in every 2 minutes? 

***I know this isn't supposed to be in the Issues section but I have no other way of contacting the developer.***

**Comment by miqmago** [comment]
Hi @rigobertomolina, no problem, it's right.
It's not implemented but not difficult to do:

```js
var INTERSTITIAL_CADENCE = 2000;

function nextInterstitial() {
    admob.requestInterstitialAd({
        publisherId:          "ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB",
        interstitialAdId:     "ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII",
        autoShowInterstitial: true
    });
}

function scheduleNextInterstitial(e) {
    if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
        setTimeout(nextInterstitial, INTERSTITIAL_CADENCE);
    }
}

function onDeviceReady() {
    document.removeEventListener('deviceready', onDeviceReady, false);
    document.addEventListener(admob.events.onAdClosed, scheduleNextInterstitial, false);
    nextInterstitial();
}

document.addEventListener('deviceready', onDeviceReady, false);

```


More complex flow should be implemented to control `admob.events.onAdLeftApplication`, `pause` and `resume` events (please see https://github.com/appfeel/admob-google-cordova/wiki/Events) and check if timeout is already set or not.

Please note that I haven't tested this code, so this is just an idea.
