### ISSUE TITLE
Use with Phone Gap Build

### ISSUE THREAD

**Issue by clevercommute** [appfeel/admob-google-cordova#5]
Hi -

We love this plug in. It's been a huge help for a project we are trying to get off the ground. 
One snag we hit...as we build using "Phone Gap Build" 
It gives us this error

"Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture"

Any thoughts on a resolution? (I saw the other (closed) issue regarding PGB...but I think this used to actually used to work)

Thanks!

--Josh

**Comment by sdnt** [comment]
Same issue here :(

**Comment by appfeel** [comment]
Hi @clevercommute @sdnt 
Thanks for the comments and sorry for the delay (this month was crazy with MWC... :)

I've updated to sdk 7.0.0, please, could you check if it works right now?

**Comment by clevercommute** [comment]
I'm sure Apple has you busy.

I'll be honest and say that (since I could not get the plugins to work in
the hosted environment) I un-subscribed to PGB. I just couldn't go on
paying for something which did not work. I hope you understand.

--Josh

**Comment by appfeel** [comment]
https://github.com/appfeel/admob-google-cordova/issues/6
