### ISSUE TITLE
Error with visual studio 2015 / cordova

### ISSUE THREAD

**Issue by blacksad29** [appfeel/admob-google-cordova#51]
Hello,

I have a problem when I try to compile cordova to test on my phone.

I find this error word:

FAILURE: Build failed with an exception
*What went wrong:
Execution failed for task':mergeDebugResources'.
> C:\Users\KrST\Documents\Visual Studio 2015\Projects\BlankCordovaApp1\BlankCordovaApp1\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.2.0\res\drawable-hdpi-v4\common_plus_signin_btn_icon_light_disabled.9.png: Error: File path too long on Windows, keep below 240 characters : C:\Users\KrST\Documents\Visual Studio 2015\Projects\BlankCordovaApp1\BlankCordovaApp1\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.2.0\res\drawable-hdpi-v4\common_plus_signin_btn_icon_light_disabled.9.png	

*try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.	

Error code 1 for command: cmd with args: /s,/c,""C:\Users\KrST\documents\visual studio 2015\Projects\BlankCordovaApp1\BlankCordovaApp1\platforms\android\gradlew" cdvBuildDebug -b "C:\Users\KrST\documents\visual studio 2015\Projects\BlankCordovaApp1\BlankCordovaApp1\platforms\android\build.gradle" -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"		

Can you help me?

cordially

**Comment by blacksad29** [comment]
New Error message:
UNEXPECTED TOP-LEVEL ERROR:	
java.lang.OutOfMemoryError: Java heap space	
Picked up _JAVA_OPTIONS: -Xmx512M			
FAILURE: Build failed with an exception.	
* What went wrong:	
Execution failed for task ':transformClassesWithDexForDebug'.	
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Java\jdk1.7.0_55\bin\java.exe'' finished with non-zero exit value 
*try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error code 1 for command: cmd with args: /s,/c,"C:\Users\KrST\Desktop\test\1\1\platforms\android\gradlew cdvBuildDebug -b C:\Users\KrST\Desktop\test\1\1\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

**Comment by miqmago** [comment]
It has been solved in new version, please see [plugin update instructions](https://github.com/appfeel/admob-google-cordova#plugin-update-phonegacordova-cli).

The problem was that this plugin was adding whole `com.google.android.gms:play-services:+`, right now it uses 

```xml
<framework src="com.google.android.gms:play-services-ads:+" />
```
```
