### ISSUE TITLE
TypeError: Cannot read property 'createBannerView' of undefined

### ISSUE THREAD

**Issue by JoelAH** [appfeel/admob-google-cordova#52]
Im getting the following errors in Cordova using Visual Studio 2015:
missing exec:AdMobAds.createBannerView
TypeError: Cannot read property 'createBannerView' of undefined
at Object.exec 
at Object.admob.createBannerView
at onDeviceReady

Please help

**Comment by miqmago** [comment]
@JoelAH this indicates that admob plugin is not loaded. It normally occurs when you are running in browser without `cordova prepare browser & cordova serve browser`. You should add an if before:

```js
if (window.admob) {
    admob.createBannerView(...);
}
```

If you are running in a real/emulated device, check in the chrome/safari inspector if plugin javascript files are correctly loaded (normally under `cordova/plugins/<id-of-the-plugin>/*.js`). If not, you should verify that javascript files are correctly copied under `platform/<id>/assets/` or similar. You should look for `admob.js` file. You can try to reinstall the plugin:

```
cordova plugin rm cordova-admob
cordova plugin add cordova-admob --save
```

**Comment by JoelAH** [comment]
Thanks. Im not getting the undefined when I run on a real device but Im getting this:
exec() call to unknown plugin: AdMobAds
It is also returning with the failure Callback saying Class Not FOund

**Comment by JoelAH** [comment]
Never mind. I got it to work now. Turns out Visual STudio was not picking it up because I installed using the Cordova CLI instead of just using Visual Studio itself to install. Thanks for your help.

**Comment by miqmago** [comment]
Good! Thanks, I'll improve docs (next month 😄 )

**Comment by RodrigoIbarraSanchez** [comment]
> Never mind. I got it to work now. Turns out Visual STudio was not picking it up because I installed using the Cordova CLI instead of just using Visual Studio itself to install. Thanks for your help.

How do you solve it? I have the same error but I can't solve it...
