### ISSUE TITLE
Possible Conflict with Google Maps plugin

### ISSUE THREAD

**Issue by mahmoudajawad** [appfeel/admob-google-cordova#53]
Hello,,

The plugin is amazing. it does the job perfectly. however, i had an issue making it work with my app that works with Google Maps plugin for cordova. loading an ad was breaking the map so i worked it around by loading the ad first and then load the map with the admob.events.onAdLoaded event. however, once i load the map the ad is moving to the top. it's very unclear to me why this is happening and what could i do for it.
Any suggestions?

**Comment by wasa4587** [comment]
I have the same issue

**Comment by AjawadMahmoud** [comment]
Can you mention more details so to find out where could the issue be.

**Comment by wasa4587** [comment]
i've been testing for some time. 
if the the maps loads first than admobs, the map disappear.
if admobs loads first than maps, the map is loaded on down, admobs on top, even if the bannerAtTop is false.
if the maps leads first than admobs and overlap is true, it works only the first time.
i didn't see any style/css changes, nor errors on adb

**Comment by crscaballero** [comment]
I have the same issue

When install "cordova-plugin-googlemaps" and "cordova-admob" i can not compile, but i can compile if only one of this are installed

**Comment by mahmoudajawad** [comment]
Closing this as I'm no longer attending this issue.
