### ISSUE TITLE
IOS build problem need help pls....

### ISSUE THREAD

**Issue by halkoy** [appfeel/admob-google-cordova#59]
hii,
I am trying to use this plugin with XDK and IOS platform. But XDK can not build for IOS.
my IOS target is IOS 8

.../builds/build.2016-10-07.15-22-58.76edk0.tmp/cordova_project/platforms/ios/StressOut/Plugins/cordova-admob/CDVAdMobAds.h:31:9: fatal error: 'GoogleMobileAds/GADAdSize.h' file not found
#import <GoogleMobileAds/GADAdSize.h>

**Comment by miqmago** [comment]
Please, could you remove the plugin and add it again? Use last version, 4.1.15.

Other versions had problems with `cordova-libgoogleadmobads`in some os.

**Comment by miqmago** [comment]
See https://github.com/appfeel/admob-google-cordova/issues/6#issuecomment-81850649

and https://github.com/appfeel/admob-google-cordova/issues/39#issuecomment-257080831

Please reopen if didn't help
