### ISSUE TITLE
Phonegap Build iOS Compile Error

### ISSUE THREAD

**Issue by tmdevde** [appfeel/admob-google-cordova#6]
Hi,

i used this Plugin for some month now and everything is awesome. But yesterday i tried my latest build and got some Compile Errors for iOS (Android is still fine):

```  
The following build commands failed:
	CompileC build/xxx.build/Release-iphoneos/xxx.build/Objects-normal/armv7/CDVAdMobAds.o xxx/Plugins/com.admob.google/CDVAdMobAds.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/xxx.build/Release-iphoneos/xxx.build/Objects-normal/armv7/CDVAdMobAdsAdListener.o xxx/Plugins/com.admob.google/CDVAdMobAdsAdListener.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
```
I don't know if it's me or PGB or the Plugin but i can't compile my App anymore and changed nothing to the Plugin. I made a ticket on PGB too but got no response yet.

**Comment by appfeel** [comment]
Hi, thanks for the feedback.

I will take a look. Meanwhile, you can force to use the previous version:

```
<gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.6"/>
```

Please I would appreciate if you let me know the response from PGB.

**Comment by tmdevde** [comment]
Hi, thanks for the reply.

I've got the same errors with the version you recommended. I testetd then again without the plugin and the app compiled without errors. Android works still without problems. The link to the PGB Thread is this one: http://community.phonegap.com/nitobi/topics/ios-build-failed-admob

**Comment by tmdevde** [comment]
nothing new yes...still getting the compile error

**Comment by tmdevde** [comment]
could you tell me if it's a plugin or a PGB problem? i really need to update my App.

**Comment by wbapps66** [comment]
I have the same issue. Since last week I can't update my IOS apps due to this problem.
The log says:
....Plugins/com.admob.google/CDVAdMobAds.h:31:9: fatal error: 'GoogleMobileAds/GADAdSize.h' file not found
#import <GoogleMobileAds/GADAdSize.h>

**Comment by appfeel** [comment]
Hi @tmdevde, @wbapps66 

This is a problem related to plugman, as it seems that doesn't support symlinks in plugins (which are needed for Google Admob SDK v7.0.0)

I'm working on this and trying to find a workaround, hope today can say something.

**Comment by appfeel** [comment]
Fixed now, tested and working in PGB with the latest version of the plugin v2.0.9.

Please comment if any problems again I will review.

**Comment by tmdevde** [comment]
compiling without any errors...running without any errors!

![Thank you appfeel]
(http://cdn.meme.am/instances/500x/60298850.jpg)

**Comment by appfeel** [comment]
Thanks!! :)
