### ISSUE TITLE
Android Build error

### ISSUE THREAD

**Issue by s-muntazir** [appfeel/admob-google-cordova#61]
Hi

I am trying to integrate this plugin but get's error message when i try to create apk. Below is the error message

> error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

 error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

I googled it and found that there is a problem with the library version. But i cannot change the libraries as i am using appery.io  as my platform.

Is there any work around with the plugin so that i can integrate the plugin.

the version with my platform are as below

> cordova  android 4.1.1
> cordova ios 3.9.1

Thanks

**Comment by miqmago** [comment]
Please see http://stackoverflow.com/questions/32075498/error-retrieving-parent-for-item-no-resource-found-that-matches-the-given-name
