### ISSUE TITLE
Ads work in app but no Impressions

### ISSUE THREAD

**Issue by skoreno1** [appfeel/admob-google-cordova#62]
The ads are showing fine, But i have no idea why i have had no Impressions or any activity through the ads, i have had the App running for the last few days and its had about 350 downloads. 

thankyou

**Comment by appfeel** [comment]
Normally there is a gap of time between ads and statistics. Please ensure that your publisher id and interstitial id is correct (if it is not, Admob still shows real ads but you get nothing). Also ensure banner ad unit and interstitial ad unit are correctly setup in your admob account. Also ensure that there is not `isTesting: true` in your admob settings.

**Comment by skoreno1** [comment]
The publisherId is set correctly, But not sure where i can set the `isTesting: true` I'm using phonegap build to package the app.

**Comment by appfeel** [comment]
See here https://github.com/appfeel/admob-google-cordova/wiki/setOptions

**Comment by appfeel** [comment]
Also take in mind that your account in admob needs to be approved in order to show impressions.

**Comment by skoreno1** [comment]
thankyou

**Comment by skoreno1** [comment]
yeah i have tried everything but still no luck, my account status is **Open** so still not sure why its not working, I have had over 1300 installs in the last few days so i would guess there would be at least a few impressions or clicks

**Comment by uKioops** [comment]
Hi,

I've got the same problem, no impressions since launch a week ago. I would like to make sure I've done nothing wrong. App is showing ads without a problem.

I'm only showing banner add for the moment.

My code is :
 
>  function onDeviceReady() {
>       document.removeEventListener('deviceready', onDeviceReady, false);
> 
>       // Set AdMobAds options:
>       admob.setOptions({
>         publisherId:          "ca-app-pub-xxxxxxxxxxxxxx16",  // Required
>         interstitialAdId:     "ca-app-pub-xxxxxxxxxxxxx16/bbbbbbbb89",  // Optional
> //        tappxIdiOs:           "/XXXXXXXXX/Pub-XXXX-iOS-IIII",            // Optional
> //        tappxIdAndroid:       "/XXXXXXXXX/Pub-XXXX-Android-AAAA",        // Optional
> //        tappxShare:           0.5                                        // Optional
>           isTesting:            false,
>       });
> 
>       // Start showing banners (atomatic when autoShowBanner is set to true)
>       admob.createBannerView();
> 
>       // Request interstitial (will present automatically when autoShowInterstitial is set to true)
>       admob.requestInterstitial();
>     }

My publisher ID in admob is written like this normaly : "pub-xxxxxxxxxxxxxx16" and not like in the exemple on git "ca-app-pub-xxxxxxxxxxxxxx16/bbbbbbbbbbb". Should I change it ?

For the interstitialAdId I put the Ad Unit ID given by AdMob.

Is there a problem with the code or with the ID ?

Thanks

**Comment by miqmago** [comment]
Normally that should be working. I think this is more an issue with Admob than with the plugin. Have you already asked them?

**Comment by miqmago** [comment]
Also, normally the publisher id is in the form `ca-app-pub-xxxxx/xxxxx`

**Comment by miqmago** [comment]
The steps to get your `ca-app-pub` code are the following ones:

- Login to your Admob account
- Go to `Monetize` tab
- Press `+ Monetize new app`
- Finish the process and you'll get your `ca-app-pub` banner code

the `pub-xxxxxx` is your publisher id code, not your banner ad unit code!
Hope it helps

**Comment by uKioops** [comment]
So the publisher id requested in the script, is the banner ad unit code ?

This would explain the problem !

**Comment by miqmago** [comment]
Yes, @skoreno1 does it solve your problem too?

**Comment by uKioops** [comment]
Ok great ! that could be confusing for noob like me x)

Thanks a lot for the fast answer :)

**Comment by uKioops** [comment]
Ok it's working now :) the impressions data will take 48h to show I think, but my House Ad campaign is now working so that's great. 

Thanks again.

**Comment by srdavidsilva** [comment]
Hello,
Sorry to reopen the topic, but I believe it's related.
From time to time, one of my apps started to display only one ad: Visual Scale (Cited at the home of this plugin).
In addition, my ad has stopped earning.
I'm trying to understand the problem, when I change the plugin, it displays another ad, but still only one. Maybe it is related to my account the problem with the other plugin but, in this plugin, what is rendered is not mine, even my advertisement being configured.

**Comment by miqmago** [comment]
Please see https://github.com/appfeel/admob-google-cordova/issues/71

**Comment by doineedajacket** [comment]
I am having the same issue. Setup admob account and have 0 impressions despite 100s of app installs. Can't find any help or contact info in admob portal. Any help would be hugely appreciated. 

My code is simply in my index.html file. Ads are showing properly, but no impressions or clicks.

```
<script>
 document.addEventListener("deviceready", function( ) { admob.createBannerView( "ca-app-pub-[pubID]/[bannerID]" ); } , false);
</script>

```

thanks in advance...

**Comment by Mandarss111** [comment]
can anyone solve my problem.My admon ads shows on app all ads banner ads and interestitial ads but not showing clicks and revenue.As i first time click on interestitial ads to confirm that how much can i earn from one click please solve my problemp

**Comment by gmp009** [comment]
Same happening with me my ads ids are correct everything from code wise is correct, but I am not seeing any Requests, Impressions all are on Zero despite of having 200 active users on app.

**Comment by RamiHtira** [comment]
Hello
My admob is displayed on the app all banner ads, interest and video reward ads.
the question :
is it normal to have 5000 requests and 1490 impressions?
thank you in advance

**Comment by sinannsekerr** [comment]
Hello, now i have same problem. Did you do anything for that? Did you solve it? I really need an answer...

**Comment by RadianDRZ** [comment]
I have AdMob, InMobi, Facebook Ads Network, and AppLovin and I have some requests, I know users are getting ads, but I don't have impressions.  I'm using Godot plugins, have AdMob ID in the AndroidManifest.xml and a few adjustments to build.gradle.   Meanwhile, AdMob and the others are making good money on us serving their ads for free.
