### ISSUE TITLE
How to call/kill ads within app?

### ISSUE THREAD

**Issue by jamminjames** [appfeel/admob-google-cordova#63]
I could use some help with firing and stopping the ads. I've got it installed, and it's working (interstitials are showing), but they're pretty random, and I don't understand how to control them. It would be nice if there were some real step-by-step instructions for newbies like me.

I've read the Wiki, but I'm still not sure how to call an ad and how to kill it so it doesn't reappear within the app. I am using Phonegap Build and jQuery Mobile, and have the 'Complete example code' set up as a .js file that is called in the head, with the "admob.createBannerView();" and "admob.requestInterstitialAd();" lines. But I'm trying to figure out mainly two things at this point:

How can I make ads appear when someone goes to a certain page? I figured I'd need a small script set up on said page, triggered by the page initialization, so I put this on the page:
`$(document).on("pageinit", function() {
  admob.showBannerAd(show, success, fail); 
}`
... am I on the right track with that? The banner ads are not appearing, so I'm not doing something right, obviously.

Also, where do you put the "admob.destroyBannerView();" line to remove the banner ad? Is there a way to create a way to "X out" the ads, so people can just get rid of them themselves?

I also have the timed interstitial ads section, as in the example, but that doesn't seem to be working, they're not appearing at timed intervals. How do you trigger that?

Thanks for any help.

**Comment by jamminjames** [comment]
Okay, I've made some progress on this, but still have questions.
Instead of the above, I've added a script with this code to load a banner ad, and it's working (and the same wrapper for interstitials):
`<script>
   function onAdLoaded(e) {
     admob.showBannerAd();
   }
</script>`

My questions are:

1. As people navigate around the app, should I call a new banner ad, and if so, how, and do I need to destroy the original one first?
I tried this, but it stopped working:
`<script>
   function onAdLoaded(e) {
     admob.destroyBannerView(); 
     admob.showBannerAd();
   }
</script>`

2. For the Interstitial, I'm using the timed ad, as per the example in Wiki:
`<script>
   function onAdLoaded(e) {
      admob.destroyBannerView();
      if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
        admob.showInterstitialAd();
        showNextInterstitial = setTimeout(function() {
          admob.requestInterstitialAd();
        }, 2 * 60 * 1000); // 2 minutes
      }
   }
</script> `
How do you stop that timed ad from appearing?

Thanks for any help.

**Comment by miqmago** [comment]
The interstitial ads are shown automatically by default (see https://github.com/appfeel/admob-google-cordova/wiki/setOptions, `autoShowBanner` and `autoShowInterstitial`)

I would recommend you to leave `autoShowBanner: true` and `autoShowInterstitial: false`.

To destroy banners it is right, you can call `admob.destroyBannerView();`. You'll have to call `admob.createBannerView();` when you want them to appear again.

Interstitials is a little bit tricky. Check this code:

```js
var isAppForeground = true;
var isInterstitialAvailable = false;


function onAdLoaded(e) {
    if (isAppForeground) {
        if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
            isInterstitialAvailable = true;
        }
    }
}

function onAdClosed(e) {
    if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
        isInterstitialAvailable = false;
        admob.requestInterstitialAd();
    }
}

function onPause() {
    if (isAppForeground) {
        admob.destroyBannerView();
        isAppForeground = false;
    }
}

function onResume() {
    if (!isAppForeground) {
        setTimeout(admob.createBannerView, 1);
        setTimeout(admob.requestInterstitialAd, 1);
        isAppForeground = true;
    }
}

// optional, in case respond to events
function registerAdEvents() {
    document.addEventListener(admob.events.onAdLoaded, onAdLoaded);
    document.addEventListener(admob.events.onAdClosed, onAdClosed);

    document.addEventListener('pause', onPause, false);
    document.addEventListener('resume', onResume, false);
}

function initAds() {
    var adPublisherIds = {
        ios: {
            banner: 'ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB',
            interstitial: 'ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII',
        },
        android: {
            banner: 'ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB',
            interstitial: 'ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII',
        }
    };

    var admobid = (/(android)/i.test(navigator.userAgent)) ? adPublisherIds.android : adPublisherIds.ios;

    admob.setOptions({
        publisherId: admobid.banner,
        interstitialAdId: admobid.interstitial,
        tappxIdiOS: '/XXXXXXXXX/Pub-XXXX-iOS-IIII',
        tappxIdAndroid: '/XXXXXXXXX/Pub-XXXX-Android-AAAA',
        tappxShare: 0.5,
        autoShowInterstitial: false,
    });

    registerAdEvents();
}

function onDeviceReady() {
    document.removeEventListener('deviceready', onDeviceReady, false);

    if (window.admob) {
        initAds();
        // request an interstitial at the beginning, it will take some time to be available
        admob.requestInterstitialAd();
    } else {
        console.error('AdMobAds plugin not ready');
    }
}
document.addEventListener('deviceready', onDeviceReady, false);

//
// Manage this events in your app:
//
function onEnterSomeScreenWithBanners() {
    if (window.admob) {
        admob.createBannerView();
    }
}

function onLeaveSomeScreenWithBanners() {
    if (window.admob) {
        admob.createBannerView();
    }
}

function onSomeEventToShowInterstitial() {
    if (window.admob) {
        if (isInterstitialAvailable) {
            admob.showInterstitialAd();
        } else {
            console.log('No interstitial available at this moment :(');
            admob.requestInterstitialAd();
        }
    }
}
```

Please reopen again if more help needed.

**Comment by jamminjames** [comment]
Thanks. You didn't answer the question about new banner ads, which I asked because I don't know what the default behavior is: Do the banner ads change on their own, or will the same ad stay there unless it's destroyed? Also, if it must be done manually in the code, is it a good idea to change the ad? It seems like it would be, as people may not respond to one ad, but they might respond to another.

The same goes for the interstitials: do they change automatically, and if not, would it be a good idea to force them to, and if so, how do you do that?

**Comment by miqmago** [comment]
> Do the banner ads change on their own, or will the same ad stay there unless it's destroyed?

The autorefresh timing is a parameter that can be set up in your Admob account at banner unit config. The rotation is managed by Admob, so they may want to show the same banner or a new one (normal behavior) for your app/user pair. You can set-up the interval to a new banner ad request.

> The same goes for the interstitials: do they change automatically, and if not, would it be a good idea to force them to, and if so, how do you do that?

Same here: A new interstitial is requested each time `admob.requestInterstitialAd();` is called. It can be a new one (normally it is) or the old one, it depends on what Admob wants to show in your concrete app and user.
