### ISSUE TITLE
Banner ads showing but not providing revenue

### ISSUE THREAD

**Issue by rmbl21** [appfeel/admob-google-cordova#64]
I've been using this plugin for a week, and it seems to be working fine. My Interstitial ad shows up and I can see it printing in my admob analytics but i'm not seeing my banner ad reporting any traffic.

After a bit of research I noticed that by changing my banner ad configuration (admob) to show text ads only with a different color scheme it kept printing in the app a image ad and i'm still getting no traffic.

I'm not sure what to say, but it really seems like this plugin is printing someone else's banner ad.

Anyone?

**Comment by miqmago** [comment]
Please see https://github.com/appfeel/admob-google-cordova/issues/62 if this is the case. Reopen otherwise.

**Comment by miqmago** [comment]
Specially https://github.com/appfeel/admob-google-cordova/issues/62#issuecomment-256610353 and https://github.com/appfeel/admob-google-cordova/issues/62#issuecomment-256614962
