### ISSUE TITLE
if (window.admob) - not working

### ISSUE THREAD

**Issue by jamminjames** [appfeel/admob-google-cordova#66]
miqmago, 

You recommended some code in a recent thread you closed (you said I could reopen it, but I don't see how), and it used the "if (window.admob)" statement, but that seemed to stop it from working. Where do you establish window.admob?

And using the code you gave me, the interstitials keep coming back immediately after you x them out. 

Also, you didn't answer the question about new banner ads, which I asked because I don't know what the default behavior is: Do the banner ads change on their own, or will the same ad stay there unless it's destroyed? Also, if it must be done manually in the code, is it a good idea to change the ad? It seems like it would be, as people may not respond to one ad, but they might respond to another.

The same goes for the interstitials: do they change automatically, and if not, would it be a good idea to force them to, and if so, how do you do that?

I appreciate your help.

**Comment by miqmago** [comment]
Reopen the issue with the gray button at left side of the green one "Comment" (normally should be there).

Second and third questions responded in old thread https://github.com/appfeel/admob-google-cordova/issues/63#issuecomment-258701763.

Please show your complete code (index.html and javascript files). Paste the code for each file, select it one by one and press the button in the comment bar `<>` which makes whole selected text to appear as code (or wrap each part of code with three ticks ``` at the beginning and at the end in a new line). After the three ticks ``` you can place 'html' for html files or 'js' for javascript files.

`window.admob` is automatically defined by cordova when the plugin is added. Normally it should work in emulator and real devices (it does not work in browser due to cordova obvious limitations).

**Comment by jamminjames** [comment]
I use PhoneGap Build, so admob is installed via the config file. I was testing in the android (v5) device, not in a browser. 

Here's the relevant part of the index.html file (in the head section I use <script src="js/admob-prepare.js"></script> to call the admob file, shown below). Notice the script at the bottom of this index file, that's how I'm bringing in the banner ad. I'm bringing in the interstitial on another page, after destroying the banner, shown below:

`<div data-role="page" id="main" data-theme="b">

	<div data-role="header">
		<h1>Humor Times: The News in Cartoons</h1>
	</div>

	<div data-role="content" style="margin:0 5%">
		<div class="logo-ht">
		<img class="ctr" src="img/HT-Sunrise-300w.gif" alt="Humor Times"></img>
		<h6><em>presents</em></h6>
		<h3>The News in Cartoons!</h3>
		</div>
		<p><strong>Review the news the fun way!</strong> And now that you've found your comic relief, don't keep it all to yourself -- share <strong><em>The News in Cartoons</em></strong> with everyone you know!</p>	

		<p><a href="cartoons0.html" data-ajax="false" data-role="button" data-transition="pop" data-icon="star">The News in Cartoons</a></p>	
		<p><a href="#previous" data-role="button" data-rel="dialog" data-transition="pop" data-icon="carat-r">Recent "News in Cartoons"</a></p>
		<p><a href="aboutpremium.html" data-role="button" data-transition="fade" data-icon="shop">Premium Version Info</a></p>	
		<p><a href="http://www.humortimes.com" rel="external" data-role="button" data-icon="action">Humor Times website</a></p>
		<p><a href="https://www.omsoft.com/secure/humortimes/subs-ht.asp" rel="external" data-role="button" data-icon="edit">HT magazine subscriptions</a></p>
		<p><a href="#about" data-role="button" data-icon="grid">About</a></p>	
		
	</div>
	
	<div data-role="footer" data-theme="b">
		<button onclick="window.plugins.socialsharing.share('Check out the Humor Times News in Cartoons app -- the fun way to review the news!', 'Humor Times News in Cartoons app', 'http://www.humortimes.com/wp-content/uploads/images1/HT-Sunrise-NewsCartoon-300w.jpg', 'http://www.humortimes.com/more/about-humor-times/')" class="ui-btn-left" data-icon="arrow-r" data-theme="b">Share the fun!</button>
        <button name="buttonClick" class="ui-btn-right" onclick="exitFromApp()">Exit</button>
	</div>
<script>
function onAdLoaded(e) {
   if (window.admob) {
       admob.showBannerAd();
   }
}
</script>
</div>`

Here's the admob-prepare.js, with my Publisher Id removed:
`var isAppForeground = true;
var isInterstitialAvailable = false;


function onAdLoaded(e) {
    if (isAppForeground) {
        if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
            isInterstitialAvailable = true;
        }
    }
}

function onAdClosed(e) {
    if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
        isInterstitialAvailable = false;
        admob.requestInterstitialAd();
    }
}

function onPause() {
    if (isAppForeground) {
        admob.destroyBannerView();
        isAppForeground = false;
    }
}

function onResume() {
    if (!isAppForeground) {
        setTimeout(admob.createBannerView, 1);
        setTimeout(admob.requestInterstitialAd, 1);
        isAppForeground = true;
    }
}

// optional, in case respond to events
function registerAdEvents() {
    document.addEventListener(admob.events.onAdLoaded, onAdLoaded);
    document.addEventListener(admob.events.onAdClosed, onAdClosed);

    document.addEventListener('pause', onPause, false);
    document.addEventListener('resume', onResume, false);
}

function initAds() {
    var adPublisherIds = {
        ios: {
            banner: 'ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB',
            interstitial: 'ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII',
        },
        android : {
            banner: 'ca-app-pub-XXXXXXXXXXXXXXXX/BBBBBBBBBB',
            interstitial: 'ca-app-pub-XXXXXXXXXXXXXXXX/IIIIIIIIII',
        }
    };

    var admobid = (/(android)/i.test(navigator.userAgent)) ? adPublisherIds.android : adPublisherIds.ios;

    admob.setOptions({
        publisherId: admobid.banner,
        interstitialAdId: admobid.interstitial,
        tappxIdiOS: '/XXXXXXXXX/Pub-XXXX-iOS-IIII',
        tappxIdAndroid: '/XXXXXXXXX/Pub-XXXX-Android-AAAA',
        tappxShare: 0.5,
        adSize:               admob.AD_SIZE.SMART_BANNER,
	    bannerAtTop:          false,
	    overlap:              false,
	    offsetStatusBar:      false,
	    isTesting:            true,
	    autoShowBanner:       false,
	    autoShowInterstitial: false
    });

    registerAdEvents();
}

function onDeviceReady() {
    document.removeEventListener('deviceready', onDeviceReady, false);
        initAds();
        // get banner ready at startup
        admob.createBannerView();
        // request an interstitial at the beginning, it will take some time to be available
        admob.requestInterstitialAd();
}
document.addEventListener('deviceready', onDeviceReady, false);`

The page where I show the interstitial has this bit of script:

` function onAdLoaded(e) {
    admob.destroyBannerView();
    if (window.admob) {
        if (isInterstitialAvailable) {
            admob.showInterstitialAd();
        } else {
            console.log('No interstitial available at this moment :(');
            admob.requestInterstitialAd();
        }
    }
  }`

**Comment by miqmago** [comment]
- If you are using PGB, then in your config.xml should be present this tag:

```xml
<gap:plugin name="phonegap-admob" source="npm"/>
```

- The admob events (`onAdLoaded`, `onAdClosed` etc.) they are both called for banners and interstitials. In the `e` parameter you'll see if it is a banner or interstitial and you need to filter each type. Learn more about events here: https://github.com/appfeel/admob-google-cordova/wiki/Events. Moreover, if the event is called you don't need to filter if `window.admob` is present (it will be as it is the source of the event):

```js
function onAdLoaded(e) {
   if (e.adType === admob.AD_TYPE.BANNER) {
       admob.showBannerAd();
   }
}
```

- I would remove this bit of code and make `autoShowBanner: true`. Then you can simply call `admob.createBannerView()` and `admob.destroyBannerView()` as many times as you need and forget to manage if banner ad is loaded. `onLoaded` events for banners are raised each time a new banner is loaded, so it means that if you have a refresh of 30s, the event will be called every 30s (very unperformant ad this is not the behavior you need).

- I would not destroy banner ads when you show interstitials, so when the interstitial is gone, the banner ads will still be there (but this is up to you), and again, you need to filter `onAdLoaded` by the `adType` and remove `window.admob`:

```js
function onAdLoaded(e) {
    if (e.adType === admob.AD_TYPE.INTERSTITIAL) {
        if (isInterstitialAvailable) {
            admob.showInterstitialAd();
        } else {
            console.log('No interstitial available at this moment :(');
            admob.requestInterstitialAd();
        }
    }
  }
```

- Finally, in your `onDeviceReady` I'd check if admob is present, just to ensure that the app is not crashing if it is not:

```js
function onDeviceReady() {
    document.removeEventListener('deviceready', onDeviceReady, false);
    if (window.admob) {
        initAds();
        // ---get banner ready at startup---
        // If you make autoShowBanner: true, this will start showing banners automatically.
        // So when autoShowBanner: true, ensure to make this call when you need to show banners
        admob.createBannerView();
        // request an interstitial at the beginning, it will take some time to be available
        admob.requestInterstitialAd();
    }
}
```

**Comment by miqmago** [comment]
Please reopen if suggestions does not work
