### ISSUE TITLE
Ads not showing in IOS. It works fine in Android

### ISSUE THREAD

**Issue by s-muntazir** [appfeel/admob-google-cordova#67]
Hi

i am using ionic app and the ads are working perfect in android apps. But nothing appears in IOS. there is no error message at all

cordova ios version :  3.9.1
cordova android version: 4.1.1

Any idea what can be the issue ?

Thanks

**Comment by miqmago** [comment]
It might be that Admob is not serving ads for your ios platform (quite strange but possible).

You could listen to [`onAdLoaded` and `onAdFailedToLoad` events](https://github.com/appfeel/admob-google-cordova/wiki/Events#admobeventsonadfailedtoload) and see what's going on in ios device (debugging with safari):

```js
document.addEventListener(admob.events.onAdLoaded, function (e) {
    console.log('All went fine', e.adType === admob.AD_TYPE.BANNER ? 'Banner', 'Interstitial');
});

document.addEventListener(admob.events.onAdFailedToLoad, function (e) {
    console.log('Error occured', JSON.stringify(e));
});
```

**Comment by s-muntazir** [comment]
It's strange because i was using ither admob plugin without tappx and it
was working fine in ios

It's only with  this plugin that it stopped ios. I will try what you
suggested and let you know the result

On 8 Nov 2016 7:11 pm, "Miquel" <notifications@github.com> wrote:

It might be that Admob is not serving ads for your ios platform (quite
strange but possible).

You could listen to onAdLoaded and onAdFailedToLoad events
<https://github.com/appfeel/admob-google-cordova/wiki/Events#admobeventsonadfailedtoload>
and see what's going on in ios device (debugging with safari):

document.addEventListener(admob.events.onAdLoaded, function (e) {
    console.log('All went fine', e.adType === admob.AD_TYPE.BANNER ?
'Banner', 'Interstitial');
});
document.addEventListener(admob.events.onAdFailedToLoad, function (e) {
    console.log('Error occured', JSON.stringify(e));
});

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/appfeel/admob-google-cordova/issues/67#issuecomment-259072192>,
or mute the thread

**Comment by s-muntazir** [comment]
HI

I tried your suggestion, but it doesn't even enter into this condition  if
(admob) {

I think it doesnt find the plugin. I tried using window.plugins.admob . but
then it goes into the else condition. And it only happends with IOS . It
works find with android. Strange

**Comment by miqmago** [comment]
The condition normally should be

```js
if (window.admob) {
...
}
```

Which platform are you using?

**Comment by s-muntazir** [comment]
I am using    ionic and angularjs

**Comment by s-muntazir** [comment]
when i use window.admob  it alerts "plugin not ready" which means it is not
finding the plugin

**Comment by s-muntazir** [comment]
I am also using online/offline functionality in my app. And when i run it
on ios it assumes that my internet is off whereas it is really on.

And it works fine on android with the same code. So i think this plugin has
something to do with the internet connection and where it might be breaking.

**Comment by miqmago** [comment]
Are you using emulator/real device or browser/ionic serve in browser? It only works in real devices or emulators.

**Comment by miqmago** [comment]
In your project you should see `platforms/ios/plugins/cordova-admob/www/admob.js`

Also you should find `platforms/ios/<your app name>/Plugins/cordova-admob/CDVAdMobAds*.*`

**Comment by miqmago** [comment]
You can also try:

```
$ cordova platform rm ios
$ cordova platform add ios
```

**Comment by s-muntazir** [comment]
I m using real device

**Comment by s-muntazir** [comment]
it is not only in 1 app. I am using this in 2 apps and it's same in both
the apps.

**Comment by miqmago** [comment]
I'm not really sure if this is an issue with this plugin or with other plugins you are using in your apps. Also I'm not really sure that I can help you anymore with the provided info/details.
Maybe your best chance is to use the other plugin that was working.
If I can help you with technical questions just reopen the issue please.

**Comment by s-muntazir** [comment]
no problem

I will try other plugin

thanks for your prompt replies...I really appreciate it

**Comment by miqmago** [comment]
Hi again. Just to make sure, are you using `isTesting: true`? In that case, if the track advertising id in the device is disabled, it will not show ads, please see https://github.com/appfeel/admob-google-cordova/issues/68

**Comment by s-muntazir** [comment]
Hi

If that is the case it nay not work in android

But it works perfectly fine in android

**Comment by miqmago** [comment]
Hmm yes, you're right. This is strange. Maybe you can try to open safari development tools and see if the `admob.js` is there. You can also paste the console logs and XCode logs here to see if it brings some light.
