### ISSUE TITLE
not showing banner

### ISSUE THREAD

**Issue by agrapps** [appfeel/admob-google-cordova#7]
Hi, i try the demo, the place for the banner appear but only it show a black space, can anybody help me with this, im using phonegap version 4.2.0-0.24.2 and cordova 4.3.0 i follow all the steps to deploy the demo

![2015-03-17 00 02 44](https://cloud.githubusercontent.com/assets/8171199/6678936/ef6cd5e2-cc06-11e4-9c12-5f4a11f3029f.png)

**Comment by appfeel** [comment]
Hi, could you paste logCat from eclipse? Which phone and version are you using?

Thanks

**Comment by agrapps** [comment]
Hi, sorry i alredy could, there was a error on my code, its pretty easy to use!! and works awesome

admob.setOptions({
        publisherId: "ca-app-pub-XXXXXXXXXXX/xxxxxxxxxxxx",
        bannerAtTop: true, // set to true, to put banner at top
        overlap: false, // set to true, to allow banner overlap webview
        offsetStatusBar: true, // set to true to avoid ios7 status bar overlap
        isTesting: false, // receiving test ads (do not test with real ads as your account will be banned)
        autoShowBanner: true, // auto show banners ad when loaded
        autoShowInterstitial: false // auto show interstitials ad when loaded
    });
    admob.createBannerView();
    admob.showBannerAd(show, success, fail);

Works just with this lines :D
