### ISSUE TITLE
phonegap-admob & analytics-google

### ISSUE THREAD

**Issue by Galaen** [appfeel/admob-google-cordova#70]
hi,

Those 2 don't play well along on android (both are your plugins)

> Error: more than one library with package name 'com.google.android.gms'

I'm using phonegap build.

In fact it seems it's working fine if I use admob-google-cordova (your other admob plugin) even with phonegap

So is there a reason to not use this one intead of phonegap-admob when creating an app with phonegap ? 

Thanks

**Comment by miqmago** [comment]
Not really, maybe Phonegap updated their comiling system and right now they use gradle. Could you provide log for android compilation?

Which is the tag you are using?

**Comment by Galaen** [comment]
Sure,
[build.txt](https://github.com/appfeel/admob-google-cordova/files/599687/build.txt) attached

I'm using 4.1.15 tag which seems to be the last one for the "phonegap-admob" plugin
And yes phonegap is now using gradle by default:
[here](http://phonegap.com/blog/2015/09/28/android-using-gradle/)

But if there is no issue using the "cordova-admob" plugin with phonegap instead, that's what I'll be doing. This seems to work well.

Thank you

**Comment by miqmago** [comment]
Thanks, these are good news. I'll update the docs.

**Comment by noveweb** [comment]
Any solution?
