### ISSUE TITLE
Only Show Testimonial  Plugin Banner Show

### ISSUE THREAD

**Issue by srdavidsilva** [appfeel/admob-google-cordova#71]
Hello,

Between 31/10 and 01/11 my viewing rates ate falling.
What used to be about 60k views a day, became 3k and suddenly zerou.

Even my rates were zeroing, my app did not stop showing ads. But this time, a single announcement: Visual Scale.

Visual Scale from what I saw has some relation with this plugin, I do not know exactly which.

Giving a grep to the directory of my app, I noticed that the plugin loads several different id publishers into several files. Imagine that using an id to test the App while development is normal, but several?

My knowledge is still somewhat limited to understand if there is something wrong or programmed maliciously, but I find this very strange.

If someone with knowledge can help debug the plugin to help find out if something is wrong will be good, so we will be sure and prevent others from having problems.

Today, for some unexplained reason, after I commented on a problem on a topic, the exhibits reappeared. Funny.

I'm sorry to be introspective, but I'm really thinking it's something programmed. This is open source, not joking, and so little private. Is a nice plugin, it helps a lot of people and this can not happen, besides creating insecurity in people, it still disfavores the growth of the community.

I'm not accusing anyone, I just want friction, I just think it's fair to avoid this kind of problem for the maintainer of the plugin and maintain honesty with whoever uses it.

**Comment by miqmago** [comment]
As stated in the front page, the app has a 2% donation code, which explains different admob ids.

It also has a fallback to Visual Scale if Admob does not want to serve ads on your app (which has actually been removed regarding to this issue, to eliminate any confusion). So if you don't see ads in your app, it is more related to Admob willing to serve ads to your app or not. Another option you have here is to place a mediation in your Admob account and show ads from other sources (or your own ads) in case Admob has no ads for your app (or they are below an ecpm you can choose, ie 0.01).

Regarding to malicious code, there is none in the whole app. As you said, it is open source and no private code anywhere (as other plugins have, with their own compiled libraries where there may be some malicious code there).

**Comment by miqmago** [comment]
See http://stackoverflow.com/questions/40675144/admob-im-seeing-the-same-ads-over-and-over-again it may help you as well

**Comment by srdavidsilva** [comment]
Thank you Mique

As for the 2% I do not see a problem, but there was something wrong because nothing was being broadcast exactly in the last 18 days, that is, it seems that it was 100% for another admob.

Today at this time he generated some of my ads, about 700 impressions and now he stopped again.

In the settings of the Admob everything is normal, alias, this is equal to all the other apps that I have, but the placement in others is normal.

**Comment by srdavidsilva** [comment]
Mique,
For some reason no more ad requests for my account of this app in question.
When AdMob does not want to provide ads, the requests arrive and, in the reports, shows requests answered. That is, AdMob returned the json with the ad content.
In my case, after my last post, you're not having any more requests. Do you think it could be something in the plugin itself?
Today I had about a thousand users online, but only 900 requests for ads, of which 700 were answered by admob.
I have the same settings in another plugin that, even with less access, now has three times more requests.
Alias, I realize that something is wrong. For some reason my app requests are not reaching my Google account, and it's the same app, same version, even everything from 20 days ago, when everything was normal.

**Comment by miqmago** [comment]
Is this an android or ios issue? 20 days ago the plugin was updated to latest sdk. Let's see if there is some issue with this.

**Comment by srdavidsilva** [comment]
Android Issue.
Until today I still have the same problem.
It really seems like the plugin is not sending the requests to the admob.

**Comment by miqmago** [comment]
Is this an android or ios issue? 20 days ago the plugin was updated to latest sdk. Let's see if there is some issue with this.

**Comment by srdavidsilva** [comment]
My that is on the air, has not been updated with this new version of the plugin and nothing. The stranger was working and stopped by himself all of a sudden.
In my tests, I installed a new version but it also did not work.

Yes, it's Android.

**Comment by miqmago** [comment]
The only thing I could recommend you is to implement an android native app with your publisher id's and see if AdMob is serving ads to your publisher id's (there is demo code in android developer help pages).

Also you could ask AdMob team in forums to see if there is any problem with your publisher id's.
