### ISSUE TITLE
Impressions stuck at 0

### ISSUE THREAD

**Issue by tomexa** [appfeel/admob-google-cordova#73]
Hi, 
it's been a few days now that my app has been launched and that I associated it in AdMob.
Everything has been working fine, the ads are correctly displayed in Android and iOS.
But the reports on AdMob show 0 impressions... 
I know sometimes it takes time for AdMob to collect the data, but it's not even showing impressions I did more than a week ago... 
Did I forget something? A 'isTesting' param I forgot to set to false? (false is default right?)

Thanks for you help

**Comment by Sin-** [comment]
Anyone?

**Comment by miqmago** [comment]
Yes, false is default, have you ensured you placed the correct id's? See https://github.com/appfeel/admob-google-cordova/issues/62#issuecomment-256609121

Reopen if this is not the case :)
