### ISSUE TITLE
Android -> Banner shows only when switching to Lock Screen and Back

### ISSUE THREAD

**Issue by tmdevde** [appfeel/admob-google-cordova#8]
Hi,

sry to bother you again. On Android the Banner doesn't show when i open the app. When i lock the Screen and switch back to the App the Banner is there. 

This guy has the same problem but i'm on Phonegap Build with the Ionic Framework : http://stackoverflow.com/questions/21408178/admob-wont-show-the-banner-until-refresh-or-sign-in-to-google-plus

I tried:

admob.createBannerView({publisherId: admob_key});
admob.setBackgroundColor('#000000');

with no effect.

**Comment by tmdevde** [comment]
Is that only my Problem? I'm testing on a Nexus 5 with Lollipop. I tried so much now but i still can't get it to work. iOS is fine btw...

**Comment by appfeel** [comment]
Hi, I'm still working on this, I've opened an issue in google groups, it might be an Admob SDK problem, but yet to see. It isn't working in concrete versions of google play services.

https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/android/VUjq-cnmKlQ

**Comment by tmdevde** [comment]
Thank you, i hope the will be a solution soon. Please keep this Issue updated.

**Comment by appfeel** [comment]
I'm still working on this issue. Meanwhile, I can confirm that although the [phonegap demo app](https://github.com/appfeel/admob-phonegap-build-demo) is having some troubles in android (which I think they are not related to this issue as the ads are never shown in the demo app), I've tested with some production cordova/ionic apps that have this plugin integrated and it works fine, being unable to reproduce this issue and showing ads when required.

Some naive things you could give a try if you haven't yet done:

* Are you calling createBanner(..) when deviceready event is raised?

* Recently I've made an update to SDK v7.0, could you try removing the plugin and adding it again? Be sure that all the dependencies and the plugin itself are being downloaded (you will see green npm http GET ... under fetching plugin line). If it's not the case, delete it from plugman cache, as sometimes is keeping the old google play services version (mac it's normally under Users/\<username\>/.plugman/cache and in windows it should be under User/\<user\>/.plugman/cache, delete all data inside this folder)

* If you are doing local development (not phonegap build), another thing you could try is to do the following modifications:

AdMobAds.java (line 115)

```java
protected RelativeLayout adViewLayout = null;
```

AdMobAdsAdListener.java (line 47)

```java
  @Override
  public void onAdLoaded() {
    admobAds.onAdLoaded(adType);
    admobAds.cordova.getActivity().runOnUiThread(new Runnable() {
      @Override
      public void run() {
        Log.d(AdMobAds.ADMOBADS_LOGTAG, adType + ": ad loaded");
        String event = String.format("javascript:cordova.fireDocumentEvent(admob.events.onAdLoaded, { 'adType': '%s' });", adType);
        admobAds.webView.loadUrl(event);
        admobAds.adViewLayout.requestLayout();
      }
    });
  }
```

Please let me know if some of those modifications are working as I will make the proper updates in the plugin.

**Comment by tmdevde** [comment]
Hi,

thanks for the reply. So i made a new Build with Phonegap Build on 3.7.0 today but nothing changed. Admob Banner isn't visible when i open the app. When i minimize it (Lockscreen or anything else) and then get back to the app the Banner is there. 

I call createBanner() in ionic.Platform.ready(function() { }. I tried to debug it and i can see the Plugin is loading the Banner when i open the App but it isn't showing the Banner until i minimize the App. 

I can't do any changes in the Code because of Phonegap Build. I never see the code because i just plug it in. 

Here is my Plugin View from the Phonegap Build Website. Let me know if i can do anything more to help. 

![bildschirmfoto 2015-03-26 um 18 56 34](https://cloud.githubusercontent.com/assets/1597280/6853274/8e5239aa-d3ea-11e4-8ac6-080ef4958f33.png)

**Comment by appfeel** [comment]
Hi @tmdevde, please, could you try with this plugin (this is just a cloned plugin from com.admob.google and modified with the proposed changes)?

```xml
<gap:plugin name="admob.google.plugin" source="plugins.cordova.io" />
```

**Comment by tmdevde** [comment]
Hi, sry for my late answer...i missed the github mail that you answered to the issue O.O

So i tried it with your suggestion but unfortunately there is no change. I have exactly the same error.

![bildschirmfoto 2015-04-05 um 00 27 34](https://cloud.githubusercontent.com/assets/1597280/6994916/c89eb0d8-db2a-11e4-888b-5ff013762b6d.png)

**Comment by tmdevde** [comment]
are there any news?

**Comment by tmdevde** [comment]
?

**Comment by appfeel** [comment]
Hi @tmdevde, I see that you are using `admob.google.plugin`. Could you check your config.xml file?You should have this line:

```xml
<gap:plugin name="com.admob.google" source="plugins.cordova.io" />
```

**Comment by appfeel** [comment]
I deleted my previous answer (probably I had a bad day... sorry for that :). I've been testing in several devices but I can't reproduce the error.

Have you tried with a blank app? There is a demo app which you can test: https://github.com/appfeel/admob-google-demo

Also I've seen that you are using ionic, have you followed the instructions at https://github.com/appfeel/admob-google-cordova/wiki/Angular.js,-Ionic-apps?

**Comment by appfeel** [comment]
Hi @tmdevde, I've made some changes to the plugin affecting cordova android@4.0.0.
Please, could you check if it's solving this issue?

**Comment by tmdevde** [comment]
hey there. thank you for your work! i'll try and report the results to you as fast as i can.

**Comment by tmdevde** [comment]
so i tested with `<gap:plugin name="com.admob.google" source="plugins.cordova.io" />` but i get the following error:

```javascript
-pre-compile:

-compile:
    [javac] Compiling 15 source files to /project/bin/classes
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:422: error: cannot find symbol
    [javac]                 ((ViewGroup) webView.getView().getParent()).addView(adViewLayout, params);
    [javac]                                     ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:432: error: cannot find symbol
    [javac]               ViewGroup wvParentView = (ViewGroup) webView.getView().getParent();
    [javac]                                                           ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:439: error: cannot find symbol
    [javac]                 wvParentView.removeView(webView.getView());
    [javac]                                                ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:442: error: cannot find symbol
    [javac]                 webView.getView().setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT, 1.0F));
    [javac]                        ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] /project/src/com/appfeel/cordova/admob/AdMobAds.java:443: error: cannot find symbol
    [javac]                 parentView.addView(webView.getView());
    [javac]                                           ^
    [javac]   symbol:   method getView()
    [javac]   location: variable webView of type CordovaWebView
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 5 errors

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.
```

**Comment by appfeel** [comment]
```xml
<gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"/>
```

See here: https://github.com/appfeel/admob-google-cordova/issues/17

In phone gap build it's still on course (I've opened a question to phone gap build people to see how to proceed, http://community.phonegap.com/nitobi/topics/phonegap-build-and-cordova-android-4-0-0-webview-getview-problem) in ionic you should update your android platform:

```
ionic platform update android@4.0.0
```

**Comment by tmdevde** [comment]
i can't update my plutform because of PGB. I don't build local ;-).  
 this is what i get with `<gap:plugin name="com.admob.google" source="plugins.cordova.io" version="2.0.14"/>`
````
-dex:
      [dex] input: /project/bin/classes
      [dex] input: /project/CordovaLib/bin/classes.jar
      [dex] input: /project/com.google.play.services/destribution-google-play-services_lib/bin/classes.jar
      [dex] input: /project/libs/libGoogleAnalyticsV2.jar
      [dex] input: /project/libs/android-support-v4.jar
      [dex] input: /project/com.google.play.services/destribution-google-play-services_lib/libs/google-play-services.jar
      [dex] Pre-Dexing /project/CordovaLib/bin/classes.jar -> classes-4b5680a50595bb2c9b7d8de03939dd40.jar
      [dex] Pre-Dexing /project/com.google.play.services/destribution-google-play-services_lib/bin/classes.jar -> classes-dac7a33217589fe71ab1eb00d9845a4a.jar
      [dex] Pre-Dexing /project/libs/libGoogleAnalyticsV2.jar -> libGoogleAnalyticsV2-ca2c99d2505519538a4b54e1875b0f79.jar
      [dex] Pre-Dexing /project/libs/android-support-v4.jar -> android-support-v4-a53f328f37f2596c105317e4e6248242.jar
      [dex] Pre-Dexing /project/com.google.play.services/destribution-google-play-services_lib/libs/google-play-services.jar -> google-play-services-bc9607a624563358a409cf24b74a8c5a.jar
      [dex] Converting compiled files and external libraries into /project/bin/classes.dex...
       [dx] Merged dex A (68 defs/81.8KiB) with dex B (223 defs/326.3KiB). Result is 291 defs/493.2KiB. Took 0.4s
       [dx] Merged dex A (291 defs/493.2KiB) with dex B (1 defs/0.4KiB). Result is 292 defs/627.6KiB. Took 0.1s
       [dx] Merged dex A (292 defs/627.6KiB) with dex B (87 defs/113.2KiB). Result is 379 defs/998.2KiB. Took 0.1s
       [dx] Result compacted from 2243.6KiB to 1125.7KiB to save 1117.9KiB
       [dx] Merged dex A (379 defs/998.2KiB) with dex B (628 defs/645.8KiB). Result is 1007 defs/1125.7KiB. Took 0.4s
       [dx] 
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/analytics/internal/Command$1;
       [dx] 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
       [dx] 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:230)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:199)
       [dx] 	at com.android.dx.command.Main.main(Main.java:103)
       [dx] 

BUILD FAILED
/home/ec2-user/android-sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/home/ec2-user/android-sdk/tools/ant/build.xml:283: null returned: 2

Total time: 1 minute 0 seconds
```

**Comment by appfeel** [comment]
Could you send which are the plugins that are you using?

This seems to be an incompatibility with other plugin that is using android-support-v4 (which has been removed in new version of com.admob.google)

**Comment by tmdevde** [comment]
i changed nothing. please seethe plugin list i postet a couple of posts ago.

**Comment by appfeel** [comment]
I see 2 google play libraries in the compilation process:

```
      [dex] input: /project/com.google.play.services/destribution-google-play-services_lib/bin/classes.jar
      [dex] input: /project/com.google.play.services/destribution-google-play-services_lib/libs/google-play-services.jar
```

Is it a zip file what you upload to PGB? Then could you review that you are not uploading a /bin folder in your project?

Other thing that you could do is to clean the PGB app (clean and refresh the source code).

**Comment by tmdevde** [comment]
i'm using google analytics too. maybe it's that? yes i upload a zip file to PGB.

**Comment by appfeel** [comment]
Probably yes, but I don't see the plugin you're using for google analytics...

**Comment by appfeel** [comment]
We have moved the plugin to npm, don't know if this issue is still open. To try new version you could use:

```
cordova plugin add cordova-admob
```

Or 

```xml
<gap:plugin name="cordova-admob" source="npm"/>
```

It is incompatible with com.danielcwilson.plugins.googleanalytics analytics plugin, you could use cordoba-plugin-analytics (cordoba-plugin-analytics-adid to use it with IDFA) instead.

**Comment by appfeel** [comment]
https://github.com/appfeel/admob-google-cordova/pull/32
