### ISSUE TITLE
"Remove Donation Code"

### ISSUE THREAD

**Issue by csumrell** [appfeel/admob-google-cordova#80]
Hi I was thinking about implementing this plugin. However, I see this in the readme "You can also support this project by sharing 2% Ad traffic (it's not mandatory: if you are unwilling to share, please fork and remove the donation code).". What does it mean remove the donation code? Do you have code implemented in the plugin that automatically donates to you?

**Comment by appfeel** [comment]
Donation code help us to keep our interest on maintaining, resolving issues and keeping this plugin updated. Feel free to remove it if you want or use as it is to help us maintaining this plugin as the best cordova-admob plugin.
